baseURL: https://masamionakada.github.io/personal_website/ # if your site is in 'https', then make sure your base url isn't written using 'http' otherwise your sitemap would contain http (as opposeed to https) URLs. This would affect Google indexing of your URLs.
title: masamionakada
paginate: 5
theme: charlolamode



menu:
    main:
        - name: Projects
          url: projects/
          weight: 30
        - name: Articles
          url: articles/
          weight: 20
        - name: Contact
          url: contact/
          weight: 10
        # - name: new Tab
        #   url: mewtab/
        #   weight: defines order of tabs


params:
    author: Masami Nakada


    defaultTheme: auto
    # disableThemeToggle: true
    ShowShareButtons: true
    ShowReadingTime: true
    displayFullLangName: true
    ShowBreadCrumbs: true
    ShowCodeCopyButtons: true
    ShowToc: true

    profileMode:
        enabled: true
        title: Hello, I’m Masami Nakada 👋
        description: Backend Developer at [DigitaliaTec](https://digitaliatec.com) / Data Science at [Cohete](https://www.cohete.com.ar), also a Python Teacher in my free hours at [HackSpace Perú](https://hackspace.pe).
        imageUrl: "/images/profile.jpg"
        imageTitle: my image
        # imageWidth: 120
        # imageHeight: 120
        buttons:
            - name: Contact Me
              url: https://api.whatsapp.com/send/?phone=51952841852&text=Hola+Masami+me+gustaría+conocer+más+sobre+tus+trabajos&type=phone_number&app_absent=0
    mainSections:
      - articles

    socialIcons:
        - name: linkedin
          url: "https://www.linkedin.com/in/masamionakada"
        - name: email
          url: "nakada2130@gmail.com"
        - name: github
          url: "https://github.com/MasamioNakada"
        - name: instagram
          url: "https://www.instagram.com/masamionakada"



      # add more social icons. find more in svg.html file
      # - name: youtube
      #   url: yoururl
      # - name: twitter
      #   url: yoururl
      # - name: facebook
      #   url: yoururl


    # change favicon in images folder (icon for web tab)
    assets:
          favicon: "/images/favicon.ico"
          favicon16x16: "/images/favicon-16x16.png"
          favicon32x32: "/images/favicon-32x32.png"
          apple_touch_icon: "/images/apple-touch-icon.png"
          safari_pinned_tab: "/images/apple-touch-icon.png"



enableInlineShortcodes: true
enableRobotsTXT: true
enableEmoji: true
pygmentsUseClasses: true

minify:
    disableXML: true

markup:
  goldmark:
    renderer:
      unsafe: true

